### PR TITLE
Increase max file size to 5GB

### PR DESCRIPTION
**Pull request by bawolff**
The max upload size on commons is now 5GB. Increase the limit here to match.

### CODE REVIEW

**Comment by don-vip** [comment]
Thank you!
Link for background/reference: https://phabricator.wikimedia.org/T191804#9549448

**Comment by Yannf** [comment]
Thanks a lot for taking care of this great tool. Does your change apply to files currently processed?

**Comment by Yannf** [comment]
Hi, I still got `An exception occurred: MaybeEncodingError: b'(\'\\\'PicklingError("Can\\\\\\\'t pickle <class \\\\\\\'video2commons.exceptions.TaskError\\\\\\\'>: import of module \\\\\\\'video2commons.exceptions\\\\\\\' failed")\\\'\', \'"(1, <ExceptionInfo: TaskError(\\\'Sorry, but files larger than 4GB can not be uploaded even with server-side uploading. This task may need manual intervention.\\\')>, None)"\')'` for https://archive.org/details/outside-the-law-1920-by-tod-browning and https://archive.org/details/chicago-1927-by-frank-urson-and-cecil-b.-demille

**Comment by don-vip** [comment]
Yes the updated code is not deployed yet. It will be deployed with the overall upgrade of video2commons needed to fix the ongoing general failure.

**Comment by Yannf** [comment]
OK thanks. Then I will wait before submitting big videos.

**Pull request merged**
